# Generated by Django 4.1.2 on 2022-11-17 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('reviews', '0003_remove_review_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='status',
            new_name='approved',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, default='Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, default='Write your review here', max_length=500),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='profiles.userprofile'),
        ),
    ]
