# Generated by Django 4.1.2 on 2022-11-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
