# Generated by Django 4.1.2 on 2022-11-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
